@echo off
if "%~1"=="" (
  echo Usage:
  echo   flow.cmd help
  echo   flow.cmd check
  echo   flow.cmd questions -RequestDir input_requests\^<your_project^>
  echo   flow.cmd start -RunId demo-run-01
  echo   flow.cmd start -RequestDir input_requests\^<your_project^> -RunId demo-run-01
  echo   flow.cmd start -RunId demo-run-01 -MaxInputFixIterations 3 -MaxReviewFixIterations 2
  echo   flow.cmd main -InputDir generated_inputs\example -RunId demo-run-01
  echo   flow.cmd compile
  echo.
  echo Request folder pattern:
  echo   input_requests\^<your_project^>\request.md
  echo   input_requests\^<your_project^>\questions.md  optional, generated by questions
  echo   input_requests\^<your_project^>\answers.md    optional, written by you
  echo.
  echo Default if -RequestDir is omitted:
  echo   input_requests\new_project_request.md
  echo.
  echo Optional: -MaxInputFixIterations defaults to 3 and -MaxReviewFixIterations defaults to 2.
  echo No command was provided, so no workflow was started.
  echo.
  echo This window will stay open in the project folder.
  echo Type a command like:
  echo   flow.cmd check
  echo   flow.cmd questions -RequestDir input_requests\^<your_project^>
  echo   flow.cmd start -RunId demo-run-01
  echo.
  cd /d "%~dp0"
  cmd /k
  exit /b 0
)
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0flow.ps1" %*
