param(
    [Parameter(Position = 0)]
    [ValidateSet("start", "main", "questions", "check", "compile", "help")]
    [string]$Command = "start",

    [string]$RunId,
    [string]$Request = "input_requests/new_project_request.md",
    [string]$RequestDir,
    [string]$InputDir,
    [string]$OutputRoot = "generated_inputs",
    [string]$Slug,
    [int]$MaxInputFixIterations = 3,
    [int]$MaxReviewFixIterations = 2,
    [switch]$NoRun
)

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$Python = Join-Path $RepoRoot ".venv\Scripts\python.exe"

function Assert-Python {
    if (-not (Test-Path $Python)) {
        throw "Python venv not found at $Python. Create .venv and install requirements first."
    }
}

function Test-Endpoint {
    param([string]$Url)

    try {
        Invoke-WebRequest $Url -UseBasicParsing -TimeoutSec 5 | Out-Null
        Write-Host "OK  $Url"
    }
    catch {
        Write-Host "ERR $Url"
        Write-Host "    $($_.Exception.Message)"
    }
}

function Show-Help {
    Write-Host "Usage:"
    Write-Host "  flow.cmd help"
    Write-Host "  flow.cmd check"
    Write-Host "  flow.cmd questions -RequestDir input_requests\<your_project>"
    Write-Host "  flow.cmd start -RunId demo-run-01"
    Write-Host "  flow.cmd start -RequestDir input_requests\<your_project> -RunId demo-run-01"
    Write-Host "  flow.cmd start -RunId demo-run-01 -MaxInputFixIterations 3 -MaxReviewFixIterations 2"
    Write-Host "  flow.cmd main -InputDir generated_inputs\example -RunId demo-run-01"
    Write-Host "  flow.cmd compile"
    Write-Host ""
    Write-Host "Request folder pattern:"
    Write-Host "  input_requests\<your_project>\request.md"
    Write-Host "  input_requests\<your_project>\questions.md  optional, generated by questions"
    Write-Host "  input_requests\<your_project>\answers.md    optional, written by you"
    Write-Host ""
    Write-Host "Default if -RequestDir is omitted:"
    Write-Host "  input_requests\new_project_request.md"
    Write-Host ""
    Write-Host "Optional: -MaxInputFixIterations defaults to 3 and -MaxReviewFixIterations defaults to 2."
}

Set-Location $RepoRoot
Assert-Python
$env:MAX_REVIEW_FIX_ITERATIONS = "$MaxReviewFixIterations"

switch ($Command) {
    "help" {
        Show-Help
        exit 0
    }

    "start" {
        $argsList = @("prepare_workflow_inputs.py", "--output-root", $OutputRoot, "--max-input-fix-iterations", "$MaxInputFixIterations")

        if ($RequestDir) {
            $argsList += @("--request-dir", $RequestDir)
        }
        else {
            $argsList += @("--request", $Request)
        }

        if ($RunId) {
            $argsList += @("--run-id", $RunId)
        }
        if ($Slug) {
            $argsList += @("--slug", $Slug)
        }
        if ($NoRun) {
            $argsList += "--no-run"
        }

        & $Python @argsList
        exit $LASTEXITCODE
    }

    "questions" {
        if (-not $RequestDir) {
            throw "questions requires -RequestDir, for example: .\flow.cmd questions -RequestDir input_requests\browser_games"
        }

        & $Python "prepare_workflow_inputs.py" "--request-dir" $RequestDir "--questions"
        exit $LASTEXITCODE
    }

    "main" {
        if (-not $InputDir) {
            throw "main requires -InputDir, for example: .\flow.ps1 main -InputDir generated_inputs\browser-games -RunId manual-main-01"
        }

        $env:WORKFLOW_INPUT_DIR = $InputDir
        if ($RunId) {
            $env:RUN_ID = $RunId
        }

        & $Python "langgraph_workflow.py"
        exit $LASTEXITCODE
    }

    "check" {
        Write-Host "Checking model endpoints..."
        Test-Endpoint "http://localhost:11434"
        Test-Endpoint "http://localhost:11435"
        Write-Host ""
        Write-Host "Checking Python files..."
        & $Python -m py_compile "prepare_workflow_inputs.py" "langgraph_workflow.py"
        if ($LASTEXITCODE -eq 0) {
            Write-Host "Python file check completed successfully."
        }
        exit $LASTEXITCODE
    }

    "compile" {
        & $Python -m py_compile "prepare_workflow_inputs.py" "langgraph_workflow.py"
        exit $LASTEXITCODE
    }
}
