#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PYTHON="$SCRIPT_DIR/.venv/bin/python"

# Defaults
RUN_ID=""
REQUEST="input_requests/new_project_request.md"
REQUEST_DIR=""
INPUT_DIR=""
OUTPUT_ROOT="generated_inputs"
SLUG=""
MAX_INPUT_FIX_ITERATIONS=3
MAX_REVIEW_FIX_ITERATIONS=2
NO_RUN=false

show_help() {
    cat <<'EOF'
Usage:
  ./flow.sh help
  ./flow.sh check
  ./flow.sh questions --request-dir input_requests/<your_project>
  ./flow.sh start --run-id demo-run-01
  ./flow.sh start --request-dir input_requests/<your_project> --run-id demo-run-01
  ./flow.sh start --run-id demo-run-01 --max-input-fix-iterations 3 --max-review-fix-iterations 2
  ./flow.sh main --input-dir generated_inputs/example --run-id demo-run-01
  ./flow.sh compile

Request folder pattern:
  input_requests/<your_project>/request.md
  input_requests/<your_project>/questions.md  optional, generated by questions
  input_requests/<your_project>/answers.md    optional, written by you

Default if --request-dir is omitted:
  input_requests/new_project_request.md

Optional: --max-input-fix-iterations defaults to 3 and --max-review-fix-iterations defaults to 2.
EOF
}

assert_python() {
    if [ ! -f "$PYTHON" ]; then
        echo "Error: Python venv not found at $PYTHON. Create .venv and install requirements first." >&2
        exit 1
    fi
}

check_endpoint() {
    local url="$1"
    if curl -sf --max-time 5 "$url" > /dev/null 2>&1; then
        echo "OK  $url"
    else
        echo "ERR $url"
    fi
}

if [ $# -eq 0 ]; then
    show_help
    echo ""
    echo "No command was provided, so no workflow was started."
    echo ""
    echo "Type a command like:"
    echo "  ./flow.sh check"
    echo "  ./flow.sh questions --request-dir input_requests/<your_project>"
    echo "  ./flow.sh start --run-id demo-run-01"
    exit 0
fi

COMMAND="$1"
shift

while [[ $# -gt 0 ]]; do
    case "$1" in
        --run-id|-RunId)
            RUN_ID="$2"; shift 2 ;;
        --request|-Request)
            REQUEST="$2"; shift 2 ;;
        --request-dir|-RequestDir)
            REQUEST_DIR="$2"; shift 2 ;;
        --input-dir|-InputDir)
            INPUT_DIR="$2"; shift 2 ;;
        --output-root|-OutputRoot)
            OUTPUT_ROOT="$2"; shift 2 ;;
        --slug|-Slug)
            SLUG="$2"; shift 2 ;;
        --max-input-fix-iterations|-MaxInputFixIterations)
            MAX_INPUT_FIX_ITERATIONS="$2"; shift 2 ;;
        --max-review-fix-iterations|-MaxReviewFixIterations)
            MAX_REVIEW_FIX_ITERATIONS="$2"; shift 2 ;;
        --no-run|-NoRun)
            NO_RUN=true; shift ;;
        *)
            echo "Unknown argument: $1" >&2
            echo "Run './flow.sh help' for usage." >&2
            exit 1 ;;
    esac
done

cd "$SCRIPT_DIR"

case "$COMMAND" in
    help)
        show_help
        ;;

    start)
        assert_python
        export MAX_REVIEW_FIX_ITERATIONS="$MAX_REVIEW_FIX_ITERATIONS"
        args=("prepare_workflow_inputs.py"
              "--output-root" "$OUTPUT_ROOT"
              "--max-input-fix-iterations" "$MAX_INPUT_FIX_ITERATIONS")
        if [ -n "$REQUEST_DIR" ]; then
            args+=("--request-dir" "$REQUEST_DIR")
        else
            args+=("--request" "$REQUEST")
        fi
        if [ -n "$RUN_ID" ]; then
            args+=("--run-id" "$RUN_ID")
        fi
        if [ -n "$SLUG" ]; then
            args+=("--slug" "$SLUG")
        fi
        if [ "$NO_RUN" = true ]; then
            args+=("--no-run")
        fi
        "$PYTHON" "${args[@]}"
        ;;

    questions)
        assert_python
        export MAX_REVIEW_FIX_ITERATIONS="$MAX_REVIEW_FIX_ITERATIONS"
        if [ -z "$REQUEST_DIR" ]; then
            echo "Error: questions requires --request-dir, e.g.:" >&2
            echo "  ./flow.sh questions --request-dir input_requests/browser_games" >&2
            exit 1
        fi
        "$PYTHON" "prepare_workflow_inputs.py" "--request-dir" "$REQUEST_DIR" "--questions"
        ;;

    main)
        assert_python
        export MAX_REVIEW_FIX_ITERATIONS="$MAX_REVIEW_FIX_ITERATIONS"
        if [ -z "$INPUT_DIR" ]; then
            echo "Error: main requires --input-dir, e.g.:" >&2
            echo "  ./flow.sh main --input-dir generated_inputs/browser-games --run-id manual-main-01" >&2
            exit 1
        fi
        export WORKFLOW_INPUT_DIR="$INPUT_DIR"
        if [ -n "$RUN_ID" ]; then
            export RUN_ID="$RUN_ID"
        fi
        "$PYTHON" "langgraph_workflow.py"
        ;;

    check)
        assert_python
        echo "Checking model endpoints..."
        check_endpoint "http://localhost:11434"
        check_endpoint "http://localhost:11435"
        echo ""
        echo "Checking Python files..."
        "$PYTHON" -m py_compile "prepare_workflow_inputs.py" "langgraph_workflow.py"
        echo "Python file check completed successfully."
        ;;

    compile)
        assert_python
        "$PYTHON" -m py_compile "prepare_workflow_inputs.py" "langgraph_workflow.py"
        ;;

    *)
        echo "Unknown command: $COMMAND" >&2
        echo "Run './flow.sh help' for usage." >&2
        exit 1
        ;;
esac
