import json
import os
import re
from collections import defaultdict
import math

INDEX_FILE = "index/chunks.json"
TOP_K = 3
DEFAULT_CONTEXT_WINDOW = 300


def load_index():
    """Load the JSON index file generated by ingest.py"""
    if not os.path.exists(INDEX_FILE):
        raise FileNotFoundError(f"Index file {INDEX_FILE} not found. Run ingestion first.")
    with open(INDEX_FILE, 'r') as f:
        return json.load(f)


def tokenize(text):
    """Simple tokenizer: lowercase and split on non-alphanumeric"""
    return re.findall(r'\b\w+\b', text.lower())


def compute_tf_idf(chunks):
    """
    Compute TF-IDF scores for each term in each chunk.
    Returns:
        tf: dict of term frequencies per chunk
        idf: dict of inverse document frequencies per term
    """
    tf = {}
    df = defaultdict(int)  # document frequency
    total_chunks = len(chunks)

    for chunk in chunks:
        chunk_id = chunk['chunk_id']
        tokens = tokenize(chunk['content'])
        tf[chunk_id] = defaultdict(float)
        seen_terms = set()

        for token in tokens:
            tf[chunk_id][token] += 1
            if token not in seen_terms:
                df[token] += 1
                seen_terms.add(token)

        # Normalize term frequencies by chunk length
        length = len(tokens)
        if length > 0:
            for term in tf[chunk_id]:
                tf[chunk_id][term] /= length

    # Compute IDF
    idf = {term: math.log(total_chunks / freq) for term, freq in df.items()}

    return tf, idf


def score_chunks(query, chunks):
    """
    Score chunks based on TF-IDF similarity to query.
    Falls back to simple keyword count if TF-IDF fails.
    """
    try:
        tf, idf = compute_tf_idf(chunks)
        query_tokens = tokenize(query)
        scores = {}

        for chunk in chunks:
            chunk_id = chunk['chunk_id']
            score = 0.0
            for token in query_tokens:
                if token in tf[chunk_id] and token in idf:
                    score += tf[chunk_id][token] * idf[token]
            scores[chunk_id] = score

        return scores

    except Exception as e:
        print(f"[WARNING] TF-IDF scoring failed ({e}), falling back to keyword matching.")

        # Fallback: simple keyword count
        scores = {}
        query_terms = set(tokenize(query))
        for chunk in chunks:
            content_tokens = set(tokenize(chunk['content']))
            match_count = len(query_terms.intersection(content_tokens))
            scores[chunk['chunk_id']] = match_count

        return scores


def extract_context_snippet(content, query, window_size=DEFAULT_CONTEXT_WINDOW):
    """Extract a snippet of text around the first occurrence of any query term."""
    query_terms = tokenize(query)
    if not query_terms:
        return content[:window_size]

    pattern = '|'.join(re.escape(term) for term in query_terms)
    match = re.search(pattern, content, re.IGNORECASE)

    if not match:
        return content[:window_size]

    start = max(0, match.start() - window_size // 2)
    end = min(len(content), match.end() + window_size // 2)
    return content[start:end]
